In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([
    [ 1,2,3 ] ,
    [4,5,6]
])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a3 = np.array([ [[ [1,2,3] , [4,5,6] ],[ 7,8,9] ]] , dtype=object)
a3

array([[list([[1, 2, 3], [4, 5, 6]]), list([7, 8, 9])]], dtype=object)

In [9]:
a3

array([[list([[1, 2, 3], [4, 5, 6]]), list([7, 8, 9])]], dtype=object)

In [10]:
type(a3)

numpy.ndarray

# Creating Arrays

In [12]:
ones = np.ones((5,3))

In [13]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
zeros = np.zeros((2,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
range = np.arange(0,20,1)
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
random = np.random.random(size=(4,3))
random

array([[0.80958597, 0.49645488, 0.89291419],
       [0.64143523, 0.94533551, 0.65890752],
       [0.5763115 , 0.44573436, 0.50620671],
       [0.11837435, 0.03150781, 0.64768763]])

In [18]:
random.size

12

In [26]:
# random.seed keeps random numbers same so that some one else on team gets the same results as us
np.random.seed(2)
rand  = np.random.rand(4,2,1,5)
rand

array([[[[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ]],

        [[0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728]]],


       [[[0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987]],

        [[0.78533515, 0.85397529, 0.49423684, 0.84656149, 0.07964548]]],


       [[[0.50524609, 0.0652865 , 0.42812233, 0.09653092, 0.12715997]],

        [[0.59674531, 0.226012  , 0.10694568, 0.22030621, 0.34982629]]],


       [[[0.46778748, 0.20174323, 0.64040673, 0.48306984, 0.50523672]],

        [[0.38689265, 0.79363745, 0.58000418, 0.1622986 , 0.70075235]]]])

In [24]:
random_int = np.random.randint(0,40 , size=(4,2,2))
random_int

array([[[26, 19],
        [32, 32]],

       [[26,  8],
        [12, 10]],

       [[34,  9],
        [37,  6]],

       [[22,  6],
        [19, 18]]])

In [27]:
np.unique(random_int)

array([ 6,  8,  9, 10, 12, 18, 19, 22, 26, 32, 34, 37])

# Viewing arrays

In [32]:
a3 = np.array([ 
    [
    [1,2,3] ,
    [4,5,6]
    ] 
    ,    
    [
    [7,8,9],
    [0,4,7]
    ],    
])

In [33]:
a3.shape

(2, 2, 3)

In [34]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a3[:,:1,:2]

array([[[1, 2]],

       [[7, 8]]])

In [38]:
a1[0]

1

In [39]:
a2[0]

array([1, 2, 3])

In [40]:
a2[0][1]

2